import os, re
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

LOGO_PATH  = r"I:\Portraitpay ai\Logo 设计\PortraitpayAI.png"
BRAND_TEXT = "This template was generated by PortraitPay AI"
BRAND_URL  = "https://portraitpayai.com/"
EN_DIR     = r"I:\Portraitpay ai\Doc\合同模板设计\EN"

C_DARK  = RGBColor(0x1A,0x1A,0x2E)
C_BLUE  = RGBColor(0x00,0x78,0xD0)
C_RED   = RGBColor(0xC0,0x00,0x00)
C_WHITE = RGBColor(0xFF,0xFF,0xFF)
C_GRAY  = RGBColor(0x60,0x60,0x60)
FN      = "Arial"

def no_borders(tbl):
    tp=tbl._tbl.tblPr; tb=OxmlElement('w:tblBorders')
    for e in ('top','left','bottom','right','insideH','insideV'):
        x=OxmlElement(f'w:{e}'); x.set(qn('w:val'),'none'); x.set(qn('w:sz'),'0')
        x.set(qn('w:space'),'0'); x.set(qn('w:color'),'auto'); tb.append(x)
    tp.append(tb)

def cell_bg(cell, h):
    tc=cell._tc; tp=tc.get_or_add_tcPr(); s=OxmlElement('w:shd')
    s.set(qn('w:val'),'clear'); s.set(qn('w:color'),'auto'); s.set(qn('w:fill'),h); tp.append(s)

def cell_border(cell, c='CCCCCC'):
    tc=cell._tc; tp=tc.get_or_add_tcPr(); b=OxmlElement('w:tcBorders')
    for e in ('top','left','bottom','right'):
        x=OxmlElement(f'w:{e}'); x.set(qn('w:val'),'single'); x.set(qn('w:sz'),'4')
        x.set(qn('w:space'),'0'); x.set(qn('w:color'),c); b.append(x)
    tp.append(b)

def vcenter(cell):
    tc=cell._tc; tp=tc.get_or_add_tcPr(); v=OxmlElement('w:vAlign'); v.set(qn('w:val'),'center'); tp.append(v)

def bot_b(para, c='CCCCCC', sz='4'):
    pp=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single'); b.set(qn('w:sz'),sz)
    b.set(qn('w:space'),'1'); b.set(qn('w:color'),c); pb.append(b); pp.append(pb)

def top_b(para, c='CCCCCC', sz='4'):
    pp=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    t=OxmlElement('w:top'); t.set(qn('w:val'),'single'); t.set(qn('w:sz'),sz)
    t.set(qn('w:space'),'1'); t.set(qn('w:color'),c); pb.append(t); pp.append(pb)

def left_b(para, c='C00000', sz='16', sp='4'):
    pp=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    l=OxmlElement('w:left'); l.set(qn('w:val'),'single'); l.set(qn('w:sz'),sz)
    l.set(qn('w:space'),sp); l.set(qn('w:color'),c); pb.append(l); pp.append(pb)

def add_field_run(para, label, field):
    r=para.add_run(label); r.font.size=Pt(8); r.font.color.rgb=C_GRAY; r.font.name=FN
    if field:
        r2=para.add_run(); r2.font.size=Pt(8); r2.font.color.rgb=C_GRAY; r2.font.name=FN
        fb=OxmlElement('w:fldChar'); fb.set(qn('w:fldCharType'),'begin')
        ins=OxmlElement('w:instrText'); ins.text=field
        fe=OxmlElement('w:fldChar'); fe.set(qn('w:fldCharType'),'end')
        r2._r.append(fb); r2._r.append(ins); r2._r.append(fe)

def add_header(doc):
    sec=doc.sections[0]; hdr=sec.header
    for p in hdr.paragraphs: p.clear()
    tbl=hdr.add_table(1,2,width=Inches(6.5)); no_borders(tbl); tbl.alignment=WD_TABLE_ALIGNMENT.LEFT
    lc=tbl.cell(0,0); lc.width=Inches(0.9)
    lp=lc.paragraphs[0]; lp.paragraph_format.space_before=Pt(0); lp.paragraph_format.space_after=Pt(0)
    lp.add_run().add_picture(LOGO_PATH, width=Inches(0.60)); vcenter(lc)
    tc=tbl.cell(0,1)
    tp2=tc.paragraphs[0]
    tp2.alignment=WD_ALIGN_PARAGRAPH.RIGHT; tp2.paragraph_format.space_before=Pt(6); tp2.paragraph_format.space_after=Pt(0)
    r=tp2.add_run(BRAND_TEXT); r.font.size=Pt(8.5); r.font.color.rgb=C_BLUE; r.font.name=FN; vcenter(tc)
    pp=hdr.paragraphs[0]._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single'); b.set(qn('w:sz'),'4')
    b.set(qn('w:space'),'1'); b.set(qn('w:color'),'CCCCCC'); pb.append(b); pp.append(pb)

def add_footer(doc):
    sec=doc.sections[0]; ftr=sec.footer
    for p in ftr.paragraphs: p.clear()
    tbl=ftr.add_table(1,3,width=Inches(6.5)); no_borders(tbl); tbl.alignment=WD_TABLE_ALIGNMENT.LEFT
    c0=tbl.cell(0,0); p0=c0.paragraphs[0]; p0.paragraph_format.space_before=Pt(4)
    r0=p0.add_run(BRAND_URL); r0.font.size=Pt(8); r0.font.color.rgb=C_BLUE; r0.font.name=FN; vcenter(c0)
    c1=tbl.cell(0,1); vcenter(c1)
    c2=tbl.cell(0,2); p2=c2.paragraphs[0]; p2.alignment=WD_ALIGN_PARAGRAPH.RIGHT
    p2.paragraph_format.space_before=Pt(4); p2.paragraph_format.space_after=Pt(0)
    add_field_run(p2,"Page ","PAGE"); add_field_run(p2," of ","NUMPAGES"); vcenter(c2)
    pp=ftr.paragraphs[0]._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    t=OxmlElement('w:top'); t.set(qn('w:val'),'single'); t.set(qn('w:sz'),'4')
    t.set(qn('w:space'),'1'); t.set(qn('w:color'),'CCCCCC'); pb.append(t); pp.append(pb)

def md_to_docx(md_path, docx_path):
    with open(md_path,'r',encoding='utf-8') as f: lines=f.read().split('\n')
    doc=Document()
    sec=doc.sections[0]; sec.top_margin=Cm(2.5); sec.bottom_margin=Cm(2.5)
    sec.left_margin=Cm(3.0); sec.right_margin=Cm(3.0)
    add_header(doc); add_footer(doc)
    sty=doc.styles['Normal']; sty.font.name=FN; sty.font.size=Pt(10.5)
    i=0
    while i<len(lines):
        ln=lines[i]
        if ln.startswith('# ') and not ln.startswith('# AI'):
            t=ln[2:].strip(); p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER
            p.paragraph_format.space_before=Pt(18); p.paragraph_format.space_after=Pt(4)
            r=p.add_run(t); r.font.size=Pt(22); r.font.bold=True; r.font.color.rgb=C_DARK; r.font.name=FN
            i+=1; continue
        if ln.startswith('## '):
            t=ln[3:].strip(); p=doc.add_paragraph()
            p.paragraph_format.space_before=Pt(16); p.paragraph_format.space_after=Pt(2)
            r=p.add_run(t); r.font.size=Pt(13); r.font.bold=True; r.font.color.rgb=C_BLUE; r.font.name=FN
            bot_b(p,c='0078D0',sz='4'); i+=1; continue
        if ln.startswith('### '):
            t=ln[4:].strip(); p=doc.add_paragraph()
            p.paragraph_format.space_before=Pt(10); p.paragraph_format.space_after=Pt(2)
            r=p.add_run(t); r.font.size=Pt(11); r.font.bold=True; r.font.color.rgb=C_DARK; r.font.name=FN
            i+=1; continue
        if ln.startswith('#### '):
            t=ln[5:].strip(); p=doc.add_paragraph()
            p.paragraph_format.space_before=Pt(8); p.paragraph_format.space_after=Pt(2)
            r=p.add_run(t); r.font.size=Pt(10.5); r.font.bold=True; r.font.color.rgb=C_GRAY; r.font.name=FN
            i+=1; continue
        if ln.startswith('|'):
            tls=[]
            while i<len(lines) and lines[i].startswith('|'): tls.append(lines[i]); i+=1
            rd=[]
            for j,tl in enumerate(tls):
                if j==1: continue
                rd.append([c.strip() for c in tl.strip('|').split('|')])
            if not rd: continue
            cols=len(rd[0]); tbl=doc.add_table(rows=len(rd),cols=cols)
            tbl.alignment=WD_TABLE_ALIGNMENT.LEFT; tbl.style='Table Grid'
            for ri,rd_ in enumerate(rd):
                is_hdr=ri==0
                for ci,cv in enumerate(rd_):
                    cell=tbl.rows[ri].cells[ci]; cell.text=''
                    cp=cell.paragraphs[0]; cp.paragraph_format.space_before=Pt(3); cp.paragraph_format.space_after=Pt(3)
                    cr=cp.add_run(cv); cr.font.name=FN; cr.font.size=Pt(10)
                    if is_hdr: cr.font.bold=True; cr.font.color.rgb=C_WHITE; cell_bg(cell,'1A1A2E')
                    else: cr.font.color.rgb=C_DARK; cell_bg(cell,'F5F8FF' if ri%2==0 else 'FFFFFF')
                    cell_border(cell,'CCCCCC')
            doc.add_paragraph().paragraph_format.space_after=Pt(4); continue
        if ln.startswith('>'):
            t=ln.lstrip('>').strip(); p=doc.add_paragraph()
            p.paragraph_format.left_indent=Inches(0.3); p.paragraph_format.right_indent=Inches(0.3)
            p.paragraph_format.space_before=Pt(8); p.paragraph_format.space_after=Pt(8)
            r=p.add_run(t); r.font.size=Pt(10.5); r.font.bold=True; r.font.italic=True
            r.font.color.rgb=C_RED; r.font.name=FN; left_b(p,c='C00000',sz='16',sp='4')
            i+=1; continue
        if ln.strip() in ('---','***','___'):
            p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(4); p.paragraph_format.space_after=Pt(4)
            bot_b(p,c='CCCCCC',sz='4'); i+=1; continue
        if ln.startswith('- [ ]'):
            t=ln[5:].strip(); p=doc.add_paragraph()
            p.paragraph_format.left_indent=Inches(0.25); p.paragraph_format.space_before=Pt(2); p.paragraph_format.space_after=Pt(2)
            r=p.add_run('\u2610  '+t); r.font.name=FN; r.font.size=Pt(10.5); r.font.color.rgb=C_DARK
            i+=1; continue
        if ln.startswith('- '):
            t=ln[2:].strip(); p=doc.add_paragraph(style='List Bullet')
            p.paragraph_format.left_indent=Inches(0.25); p.paragraph_format.space_before=Pt(2); p.paragraph_format.space_after=Pt(2)
            for pi,pt in enumerate(re.split(r'\*\*(.*?)\*\*',t)):
                r=p.add_run(pt); r.font.name=FN; r.font.size=Pt(10.5); r.font.color.rgb=C_DARK
                if pi%2==1: r.font.bold=True
            i+=1; continue
        m=re.match(r'^\d+\.\s',ln)
        if m:
            t=re.match(r'^\d+\.\s+(.*)',ln).group(1); p=doc.add_paragraph(style='List Number')
            p.paragraph_format.left_indent=Inches(0.3); p.paragraph_format.space_before=Pt(2); p.paragraph_format.space_after=Pt(2)
            for pi,pt in enumerate(re.split(r'\*\*(.*?)\*\*',t)):
                r=p.add_run(pt); r.font.name=FN; r.font.size=Pt(10.5); r.font.color.rgb=C_DARK
                if pi%2==1: r.font.bold=True
            i+=1; continue
        if not ln.strip(): i+=1; continue
        p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(2); p.paragraph_format.space_after=Pt(4)
        for pi,pt in enumerate(re.split(r'\*\*(.*?)\*\*',ln)):
            r=p.add_run(pt); r.font.name=FN; r.font.size=Pt(10.5); r.font.color.rgb=C_DARK
            if pi%2==1: r.font.bold=True
        i+=1
    doc.save(docx_path)
    sz=os.path.getsize(docx_path)//1024
    print(f"[OK] {os.path.basename(docx_path):55s}  ({sz} KB)")

files=[
    ('00-Overview-Guide.docx.md',                    '00-Overview-and-Signing-Guide.docx'),
    ('01-Standard-License-Agreement.docx.md',        '01-Standard-License-Agreement.docx'),
    ('02-Exclusive-License-Agreement.docx.md',        '02-Exclusive-License-Agreement.docx'),
    ('03-Endorsement-License-Agreement.docx.md',      '03-Endorsement-License-Agreement.docx'),
    ('04-Film-Adaptation-License-Agreement.docx.md', '04-Film-Adaptation-License-Agreement.docx'),
]
for mn,dn in files:
    md_to_docx(os.path.join(EN_DIR,mn), os.path.join(EN_DIR,dn))
print("\nDone -- header: smaller logo, blue text only; footer unchanged.")
