import os
import re
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

LOGO_PATH = r"I:\Portraitpay ai\Logo 设计\PortraitpayAI.png"
BRAND_TEXT = "This template was generated by PortraitPay AI"
BRAND_URL  = "https://portraitpayai.com/"
EN_DIR     = r"I:\Portraitpay ai\Doc\合同模板设计\EN"

COLOR_DARK    = RGBColor(0x1A, 0x1A, 0x2E)
COLOR_ACCENT  = RGBColor(0x00, 0x78, 0xD0)
COLOR_RED     = RGBColor(0xC0, 0x00, 0x00)
COLOR_WHITE   = RGBColor(0xFF, 0xFF, 0xFF)
FONT_BODY     = "Arial"
FONT_HEADING  = "Arial"

# ─── XML helpers ───────────────────────────────────────────────────────────────

def set_cell_bg(cell, hex_color):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement('w:shd')
    shd.set(qn('w:val'),   'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'),  hex_color)
    tcPr.append(shd)

def set_cell_border(cell, color='CCCCCC'):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcB  = OxmlElement('w:tcBorders')
    for edge in ('top','left','bottom','right'):
        tag = OxmlElement(f'w:{edge}')
        tag.set(qn('w:val'),   'single')
        tag.set(qn('w:sz'),    '4')
        tag.set(qn('w:space'), '0')
        tag.set(qn('w:color'), color)
        tcB.append(tag)
    tcPr.append(tcB)

def add_bottom_border(para, color='0078D0', sz='6'):
    pPr = para._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bot  = OxmlElement('w:bottom')
    bot.set(qn('w:val'),   'single')
    bot.set(qn('w:sz'),    sz)
    bot.set(qn('w:space'), '1')
    bot.set(qn('w:color'), color)
    pBdr.append(bot)
    pPr.append(pBdr)

def add_left_border(para, color='C00000', sz='16', space='4'):
    pPr = para._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    left = OxmlElement('w:left')
    left.set(qn('w:val'),   'single')
    left.set(qn('w:sz'),    sz)
    left.set(qn('w:space'), space)
    left.set(qn('w:color'), color)
    pBdr.append(left)
    pPr.append(pBdr)

def set_cell_vertical_center(cell):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    vAlign = OxmlElement('w:vAlign')
    vAlign.set(qn('w:val'), 'center')
    tcPr.append(vAlign)

# ─── Header / Footer ───────────────────────────────────────────────────────────

def add_logo_header(doc):
    section = doc.sections[0]
    header  = section.header

    # Logo + brand text in a table (left: logo, right: text)
    tbl = header.add_table(1, 2, width=Inches(6.5))
    tbl.style = 'Table Grid'
    tbl.alignment = WD_TABLE_ALIGNMENT.LEFT

    # Remove all borders on header table
    tbl_pr = tbl._tbl.tblPr
    tbl_borders = OxmlElement('w:tblBorders')
    for edge in ('top','left','bottom','right','insideH','insideV'):
        tag = OxmlElement(f'w:{edge}')
        tag.set(qn('w:val'),   'none')
        tag.set(qn('w:sz'),    '0')
        tag.set(qn('w:space'), '0')
        tag.set(qn('w:color'), 'auto')
        tbl_borders.append(tag)
    tbl_pr.append(tbl_borders)

    # Logo cell
    logo_cell = tbl.cell(0, 0)
    logo_cell.width = Inches(1.0)
    lp = logo_cell.paragraphs[0]
    lp.paragraph_format.space_before = Pt(0)
    lp.paragraph_format.space_after  = Pt(0)
    run = lp.add_run()
    run.add_picture(LOGO_PATH, width=Inches(0.65))
    set_cell_vertical_center(logo_cell)

    # Brand text cell
    text_cell = tbl.cell(0, 1)
    tp = text_cell.paragraphs[0]
    tp.paragraph_format.space_before = Pt(4)
    tp.paragraph_format.space_after  = Pt(0)
    r1 = tp.add_run(BRAND_TEXT + " ")
    r1.font.size  = Pt(8)
    r1.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
    r1.font.name  = FONT_BODY
    r2 = tp.add_run(BRAND_URL)
    r2.font.size  = Pt(8)
    r2.font.color.rgb = COLOR_ACCENT
    r2.font.name  = FONT_BODY

    # Bottom border under header
    pPr  = header.paragraphs[0]._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bot  = OxmlElement('w:bottom')
    bot.set(qn('w:val'),   'single')
    bot.set(qn('w:sz'),    '4')
    bot.set(qn('w:space'), '1')
    bot.set(qn('w:color'), 'CCCCCC')
    pBdr.append(bot)
    pPr.append(pBdr)

def add_numbered_footer(doc):
    section = doc.sections[0]
    footer   = section.footer

    # Page X of Y style
    fpara = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    fpara.clear()

    # Add page number field
    # Left: brand URL | Center: | Right: Page X of Y
    # Use a 3-col table for clean layout
    tbl = footer.add_table(1, 3, width=Inches(6.5))
    tbl.style = 'Table Grid'

    tbl_pr = tbl._tbl.tblPr
    tbl_borders = OxmlElement('w:tblBorders')
    for edge in ('top','left','bottom','right','insideH','insideV'):
        tag = OxmlElement(f'w:{edge}')
        tag.set(qn('w:val'),   'none')
        tag.set(qn('w:sz'),   '0')
        tag.set(qn('w:space'),'0')
        tag.set(qn('w:color'), 'auto')
        tbl_borders.append(tag)
    tbl_pr.append(tbl_borders)

    # Col 0: brand URL
    c0 = tbl.cell(0, 0)
    p0 = c0.paragraphs[0]
    p0.paragraph_format.space_before = Pt(4)
    p0.paragraph_format.space_after  = Pt(0)
    r0 = p0.add_run(BRAND_URL)
    r0.font.size  = Pt(8)
    r0.font.color.rgb = COLOR_ACCENT
    r0.font.name  = FONT_BODY
    set_cell_vertical_center(c0)

    # Col 1: (empty spacer)
    c1 = tbl.cell(0, 1)
    p1 = c1.paragraphs[0]
    p1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_cell_vertical_center(c1)

    # Col 2: Page X of Y
    c2 = tbl.cell(0, 2)
    p2 = c2.paragraphs[0]
    p2.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    p2.paragraph_format.space_before = Pt(4)
    p2.paragraph_format.space_after  = Pt(0)

    run_pre = p2.add_run("Page ")
    run_pre.font.size  = Pt(8)
    run_pre.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
    run_pre.font.name  = FONT_BODY

    # PAGE field
    fldChar_begin = OxmlElement('w:fldChar')
    fldChar_begin.set(qn('w:fldCharType'), 'begin')
    instrText = OxmlElement('w:instrText')
    instrText.text = 'PAGE'
    fldChar_end = OxmlElement('w:fldChar')
    fldChar_end.set(qn('w:fldCharType'), 'end')
    run_page = p2.add_run()
    run_page.font.size  = Pt(8)
    run_page.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
    run_page.font.name  = FONT_BODY
    run_page._r.append(fldChar_begin)
    run_page._r.append(instrText)
    run_page._r.append(fldChar_end)

    run_of = p2.add_run(" of ")
    run_of.font.size  = Pt(8)
    run_of.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
    run_of.font.name  = FONT_BODY

    # NUMPAGES field
    fldChar_begin2 = OxmlElement('w:fldChar')
    fldChar_begin2.set(qn('w:fldCharType'), 'begin')
    instrText2 = OxmlElement('w:instrText')
    instrText2.text = 'NUMPAGES'
    fldChar_end2 = OxmlElement('w:fldChar')
    fldChar_end2.set(qn('w:fldCharType'), 'end')
    run_total = p2.add_run()
    run_total.font.size  = Pt(8)
    run_total.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
    run_total.font.name  = FONT_BODY
    run_total._r.append(fldChar_begin2)
    run_total._r.append(instrText2)
    run_total._r.append(fldChar_end2)
    set_cell_vertical_center(c2)

    # Top border on footer
    pPr2  = footer.paragraphs[0]._p.get_or_add_pPr()
    pBdr2 = OxmlElement('w:pBdr')
    top2  = OxmlElement('w:top')
    top2.set(qn('w:val'),   'single')
    top2.set(qn('w:sz'),    '4')
    top2.set(qn('w:space'), '1')
    top2.set(qn('w:color'), 'CCCCCC')
    pBdr2.append(top2)
    pPr2.append(pBdr2)

# ─── Parser ───────────────────────────────────────────────────────────────────

def md_to_docx(md_path, docx_path):
    with open(md_path, 'r', encoding='utf-8') as f:
        lines = f.read().split('\n')

    doc = Document()
    section = doc.sections[0]
    section.top_margin    = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin   = Cm(3.0)
    section.right_margin  = Cm(3.0)

    # Add logo header + numbered footer
    add_logo_header(doc)
    add_numbered_footer(doc)

    style = doc.styles['Normal']
    style.font.name = FONT_BODY
    style.font.size = Pt(10.5)

    i = 0
    while i < len(lines):
        line = lines[i]

        if line.startswith('# ') and not line.startswith('# AI'):
            text = line[2:].strip()
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            p.paragraph_format.space_before = Pt(18)
            p.paragraph_format.space_after  = Pt(4)
            run = p.add_run(text)
            run.font.size = Pt(22); run.font.bold = True
            run.font.color.rgb = COLOR_DARK; run.font.name = FONT_HEADING
            i += 1; continue

        if line.startswith('## '):
            text = line[3:].strip()
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(16)
            p.paragraph_format.space_after  = Pt(2)
            run = p.add_run(text)
            run.font.size = Pt(13); run.font.bold = True
            run.font.color.rgb = COLOR_ACCENT; run.font.name = FONT_HEADING
            add_bottom_border(p, color='0078D0', sz='4')
            i += 1; continue

        if line.startswith('### '):
            text = line[4:].strip()
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(10)
            p.paragraph_format.space_after  = Pt(2)
            run = p.add_run(text)
            run.font.size = Pt(11); run.font.bold = True
            run.font.color.rgb = COLOR_DARK; run.font.name = FONT_HEADING
            i += 1; continue

        if line.startswith('#### '):
            text = line[5:].strip()
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(8)
            p.paragraph_format.space_after  = Pt(2)
            run = p.add_run(text)
            run.font.size = Pt(10.5); run.font.bold = True
            run.font.color.rgb = RGBColor(0x60,0x60,0x60); run.font.name = FONT_HEADING
            i += 1; continue

        if line.startswith('|'):
            table_lines = []
            while i < len(lines) and lines[i].startswith('|'):
                table_lines.append(lines[i]); i += 1
            rows_data = []
            for j, tl in enumerate(table_lines):
                if j == 1: continue
                cells = [c.strip() for c in tl.strip('|').split('|')]
                rows_data.append(cells)
            if not rows_data: continue
            cols = len(rows_data[0])
            tbl  = doc.add_table(rows=len(rows_data), cols=cols)
            tbl.alignment = WD_TABLE_ALIGNMENT.LEFT
            tbl.style = 'Table Grid'
            for ri, row_data in enumerate(rows_data):
                is_hdr = ri == 0
                for ci, ct in enumerate(row_data):
                    cell = tbl.rows[ri].cells[ci]
                    cell.text = ''
                    cp = cell.paragraphs[0]
                    cp.paragraph_format.space_before = Pt(3)
                    cp.paragraph_format.space_after  = Pt(3)
                    cr = cp.add_run(ct)
                    cr.font.name = FONT_BODY; cr.font.size = Pt(10)
                    if is_hdr:
                        cr.font.bold = True; cr.font.color.rgb = COLOR_WHITE
                        set_cell_bg(cell, '1A1A2E')
                    else:
                        cr.font.color.rgb = COLOR_DARK
                        set_cell_bg(cell, 'F5F8FF' if ri % 2 == 0 else 'FFFFFF')
                    set_cell_border(cell, 'CCCCCC')
            doc.add_paragraph().paragraph_format.space_after = Pt(4)
            continue

        if line.startswith('>'):
            text = line.lstrip('>').strip()
            p = doc.add_paragraph()
            p.paragraph_format.left_indent  = Inches(0.3)
            p.paragraph_format.right_indent = Inches(0.3)
            p.paragraph_format.space_before = Pt(8)
            p.paragraph_format.space_after  = Pt(8)
            run = p.add_run(text)
            run.font.size = Pt(10.5); run.font.bold = True; run.font.italic = True
            run.font.color.rgb = COLOR_RED; run.font.name = FONT_BODY
            add_left_border(p, color='C00000', sz='16', space='4')
            i += 1; continue

        if line.strip() in ('---','***','___'):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after  = Pt(4)
            add_bottom_border(p, color='CCCCCC', sz='4')
            i += 1; continue

        if line.startswith('- [ ]'):
            text = line[5:].strip()
            p = doc.add_paragraph()
            p.paragraph_format.left_indent  = Inches(0.25)
            p.paragraph_format.space_before = Pt(2)
            p.paragraph_format.space_after  = Pt(2)
            run = p.add_run('☐  ' + text)
            run.font.name = FONT_BODY; run.font.size = Pt(10.5)
            run.font.color.rgb = COLOR_DARK
            i += 1; continue

        if line.startswith('- '):
            text = line[2:].strip()
            p = doc.add_paragraph(style='List Bullet')
            p.paragraph_format.left_indent  = Inches(0.25)
            p.paragraph_format.space_before = Pt(2)
            p.paragraph_format.space_after  = Pt(2)
            parts = re.split(r'\*\*(.*?)\*\*', text)
            for pi, part in enumerate(parts):
                run = p.add_run(part)
                run.font.name = FONT_BODY; run.font.size = Pt(10.5)
                run.font.color.rgb = COLOR_DARK
                if pi % 2 == 1: run.font.bold = True
            i += 1; continue

        if re.match(r'^\d+\.\s', line):
            m   = re.match(r'^(\d+)\.\s+(.*)', line)
            num, text = m.group(1), m.group(2)
            p   = doc.add_paragraph(style='List Number')
            p.paragraph_format.left_indent  = Inches(0.3)
            p.paragraph_format.space_before = Pt(2)
            p.paragraph_format.space_after  = Pt(2)
            parts = re.split(r'\*\*(.*?)\*\*', text)
            for pi, part in enumerate(parts):
                run = p.add_run(part)
                run.font.name = FONT_BODY; run.font.size = Pt(10.5)
                run.font.color.rgb = COLOR_DARK
                if pi % 2 == 1: run.font.bold = True
            i += 1; continue

        if not line.strip():
            i += 1; continue

        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(2)
        p.paragraph_format.space_after  = Pt(4)
        parts = re.split(r'\*\*(.*?)\*\*', line)
        for pi, part in enumerate(parts):
            run = p.add_run(part)
            run.font.name = FONT_BODY; run.font.size = Pt(10.5)
            run.font.color.rgb = COLOR_DARK
            if pi % 2 == 1: run.font.bold = True
        i += 1

    doc.save(docx_path)
    size = os.path.getsize(docx_path) // 1024
    print(f"[OK] {os.path.basename(docx_path):55s}  ({size} KB)")

# ─── Run ───────────────────────────────────────────────────────────────────────

files = [
    ('00-Overview-Guide.docx.md',                    '00-Overview-and-Signing-Guide.docx'),
    ('01-Standard-License-Agreement.docx.md',         '01-Standard-License-Agreement.docx'),
    ('02-Exclusive-License-Agreement.docx.md',        '02-Exclusive-License-Agreement.docx'),
    ('03-Endorsement-License-Agreement.docx.md',      '03-Endorsement-License-Agreement.docx'),
    ('04-Film-Adaptation-License-Agreement.docx.md',   '04-Film-Adaptation-License-Agreement.docx'),
]

for md_name, docx_name in files:
    md_path  = os.path.join(EN_DIR, md_name)
    docx_path = os.path.join(EN_DIR, docx_name)
    md_to_docx(md_path, docx_path)

print("\nAll English Word documents with header/footer generated!")
