"""
PortraitPay AI — Generate 4 contract templates in user's finalized style
Style: navy blue (#244169), white header logo, centered layout, zebra table
"""
import os, re
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm, Twips
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

LOGO_PATH = r"I:\Portraitpay ai\Logo 设计\PortraitpayAI.png"
BRAND_TEXT = "This template was generated by PortraitPay AI"
BRAND_URL  = "portraitpayai.com"
EN_DIR     = r"I:\Portraitpay ai\Doc\合同模板设计\EN"

NAVY  = RGBColor(0x24,0x41,0x69)
WHITE = RGBColor(0xFF,0xFF,0xFF)
GRAY  = RGBColor(0x60,0x60,0x60)
DARK  = RGBColor(0x1A,0x1A,0x1A)
FN    = "Arial"

# ─── Helpers ──────────────────────────────────────────────────────────────────

def shd_cell(cell, h):
    tc=cell._tc; tp=tc.get_or_add_tcPr(); s=OxmlElement('w:shd')
    s.set(qn('w:val'),'clear'); s.set(qn('w:color'),'auto'); s.set(qn('w:fill'),h); tp.append(s)

def cell_borders(cell, c="CCCCCC", sz="4"):
    tc=cell._tc; tp=tc.get_or_add_tcPr(); b=OxmlElement('w:tcBorders')
    for e in ('top','left','bottom','right'):
        x=OxmlElement(f'w:{e}'); x.set(qn('w:val'),'single')
        x.set(qn('w:sz'),sz); x.set(qn('w:space'),'0'); x.set(qn('w:color'),c)
        b.append(x)
    tp.append(b)

def border_bottom(para, c="244169", sz="4"):
    pPr=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single')
    b.set(qn('w:sz'),sz); b.set(qn('w:space'),'1'); b.set(qn('w:color'),c)
    pb.append(b); pPr.append(pb)

def border_top(para, c="CCCCCC", sz="4"):
    pPr=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    t=OxmlElement('w:top'); t.set(qn('w:val'),'single')
    t.set(qn('w:sz'),sz); t.set(qn('w:space'),'1'); t.set(qn('w:color'),c)
    pb.append(t); pPr.append(pb)

# ─── Content builders ──────────────────────────────────────────────────────────

def h2(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(14); p.paragraph_format.space_after=Pt(3)
    # Thin grey line ABOVE section heading (not below)
    border_top(p, c="CCCCCC", sz="4")
    r=p.add_run(text.upper())
    r.font.name=FN; r.font.size=Pt(11); r.font.bold=True; r.font.color.rgb=NAVY

def h3(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(8); p.paragraph_format.space_after=Pt(2)
    r=p.add_run(text)
    r.font.name=FN; r.font.size=Pt(10.5); r.font.bold=True; r.font.color.rgb=DARK

def body(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(4); p.paragraph_format.space_after=Pt(6)
    for pi,pt in enumerate(re.split(r'\*\*(.*?)\*\*',text)):
        r=p.add_run(pt); r.font.name=FN; r.font.size=Pt(10.5); r.font.color.rgb=DARK
        if pi%2==1: r.font.bold=True

def fill_line(doc, label, chars=28):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(3); p.paragraph_format.space_after=Pt(3)
    if label:
        r1=p.add_run(label+":  "); r1.font.name=FN; r1.font.size=Pt(9.5); r1.font.color.rgb=GRAY
    r2=p.add_run("_"*chars); r2.font.name=FN; r2.font.size=Pt(9.5); r2.font.color.rgb=NAVY

def checkbox(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(2); p.paragraph_format.space_after=Pt(2)
    p.paragraph_format.left_indent=Inches(0.25)
    r=p.add_run("\u2610  "+text); r.font.name=FN; r.font.size=Pt(10); r.font.color.rgb=DARK

def parties_table(doc, a_label, b_label, a_fields, b_fields):
    n = max(len(a_fields), len(b_fields))
    tbl=doc.add_table(rows=2+n, cols=2)
    tbl.style='Table Grid'; tbl.alignment=WD_TABLE_ALIGNMENT.CENTER
    for ci,w in enumerate([Inches(3.0),Inches(3.0)]):
        for cell in tbl.columns[ci].cells: cell.width=w

    # Header row — navy bg, white text
    for ci,hdr_text in enumerate([a_label, b_label]):
        cell=tbl.rows[0].cells[ci]; cell.text=""
        pp=cell.paragraphs[0]
        pp.paragraph_format.space_before=Pt(5); pp.paragraph_format.space_after=Pt(5)
        rr=pp.add_run(hdr_text); rr.font.name=FN; rr.font.size=Pt(10); rr.font.bold=True
        rr.font.color.rgb=WHITE; shd_cell(cell,"244169"); cell_borders(cell,"1A1A1A","4")

    # Data rows — zebra: lavender #F0F2F8 / white
    for ri,(fa,fb) in enumerate(zip(a_fields,b_fields)):
        row=tbl.rows[ri+1]; row.height=Twips(400)
        bg = "F0F2F8" if ri%2==0 else "FFFFFF"
        for ci,(cell,lbl) in enumerate(zip(row.cells,[fa,fb])):
            cell.text=""; pp=cell.paragraphs[0]
            pp.paragraph_format.space_before=Pt(5); pp.paragraph_format.space_after=Pt(5)
            r1=pp.add_run(lbl+":  "); r1.font.name=FN; r1.font.size=Pt(9.5); r1.font.color.rgb=GRAY
            r2=pp.add_run("_"*25); r2.font.name=FN; r2.font.size=Pt(9.5); r2.font.color.rgb=NAVY
            shd_cell(cell,bg); cell_borders(cell,"DDDDDD","4")

    sp=doc.add_paragraph(); sp.paragraph_format.space_after=Pt(8)

def license_box(doc, lic_type, price_range):
    tbl=doc.add_table(rows=1,cols=1)
    tbl.alignment=WD_TABLE_ALIGNMENT.CENTER; tbl.style='Table Grid'
    cell=tbl.rows[0].cells[0]; cell.text=""
    pp=cell.paragraphs[0]; pp.alignment=WD_ALIGN_PARAGRAPH.CENTER
    pp.paragraph_format.space_before=Pt(8); pp.paragraph_format.space_after=Pt(8)
    rr=pp.add_run(f"LICENSE TYPE:  {lic_type}    |    FEE RANGE:  {price_range}")
    rr.font.name=FN; rr.font.size=Pt(11); rr.font.bold=True; rr.font.color.rgb=WHITE
    shd_cell(cell,"244169"); cell_borders(cell,"1A1A1A","4")
    sp=doc.add_paragraph(); sp.paragraph_format.space_after=Pt(10)

def sig_block(doc, party_a, party_b):
    labels=["Signature","Print Name","Date"]
    tbl=doc.add_table(rows=3,cols=2)
    tbl.alignment=WD_TABLE_ALIGNMENT.LEFT; tbl.style='Table Grid'
    for ri,la in enumerate(labels):
        row=tbl.rows[ri]; row.height=Twips(420)
        for ci,(cell,lbl) in enumerate(zip(row.cells,[party_a,party_b])):
            cell.text=""; pp=cell.paragraphs[0]
            pp.paragraph_format.space_before=Pt(5); pp.paragraph_format.space_after=Pt(5)
            r1=pp.add_run(lbl+" "+la+":  ")
            r1.font.name=FN; r1.font.size=Pt(9.5); r1.font.color.rgb=GRAY
            r2=pp.add_run("_"*35); r2.font.name=FN; r2.font.size=Pt(9.5); r2.font.color.rgb=NAVY
            shd_cell(cell,"F8F8F8"); cell_borders(cell,"CCCCCC","4")
    sp=doc.add_paragraph(); sp.paragraph_format.space_after=Pt(4)

def add_brand_top(doc):
    # Ensure at least one paragraph exists first
    if len(doc.paragraphs) == 0:
        doc.add_paragraph()
    first_p = doc.paragraphs[0]
    # Logo
    p1=first_p.insert_paragraph_before()
    p1.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p1.paragraph_format.space_before=Pt(4); p1.paragraph_format.space_after=Pt(6)
    p1.add_run().add_picture(LOGO_PATH, width=Inches(0.75))
    # Brand name
    p2=first_p.insert_paragraph_before()
    p2.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p2.paragraph_format.space_before=Pt(2); p2.paragraph_format.space_after=Pt(14)
    r=p2.add_run("PortraitPay AI"); r.font.name=FN; r.font.size=Pt(12); r.font.bold=True; r.font.color.rgb=NAVY
    # Separator
    p3=first_p.insert_paragraph_before()
    p3.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p3.paragraph_format.space_before=Pt(2); p3.paragraph_format.space_after=Pt(0)
    border_bottom(p3,c="244169",sz="6")

def add_url_bottom(doc):
    p=doc.add_paragraph()
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(20); p.paragraph_format.space_after=Pt(6)
    border_top(p,c="CCCCCC",sz="4")
    r=p.add_run(BRAND_URL); r.font.name=FN; r.font.size=Pt(9); r.font.color.rgb=GRAY; r.font.italic=True

def build(doc, info):
    sty=doc.styles['Normal']; sty.font.name=FN; sty.font.size=Pt(10.5)
    sec=doc.sections[0]
    sec.top_margin=Cm(2.5); sec.bottom_margin=Cm(2.5)
    sec.left_margin=Cm(2.5); sec.right_margin=Cm(2.5)

    add_brand_top(doc)

    # Title
    p=doc.add_paragraph()
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(4); p.paragraph_format.space_after=Pt(4)
    r=p.add_run(info['title']); r.font.name=FN; r.font.size=Pt(22); r.font.bold=True; r.font.color.rgb=NAVY

    if info.get('subtitle'):
        p2=doc.add_paragraph()
        p2.alignment=WD_ALIGN_PARAGRAPH.CENTER
        p2.paragraph_format.space_before=Pt(0); p2.paragraph_format.space_after=Pt(10)
        r2=p2.add_run(info['subtitle'])
        r2.font.name=FN; r2.font.size=Pt(11); r2.font.color.rgb=GRAY

    license_box(doc, info.get('license_type',''), info.get('price_range',''))

    # Parties section
    p_hdr=doc.add_paragraph()
    p_hdr.paragraph_format.space_before=Pt(8); p_hdr.paragraph_format.space_after=Pt(4)
    r_hdr=p_hdr.add_run("PARTIES TO THIS AGREEMENT")
    r_hdr.font.name=FN; r_hdr.font.size=Pt(10.5); r_hdr.font.bold=True; r_hdr.font.color.rgb=NAVY

    p_note=doc.add_paragraph()
    p_note.paragraph_format.space_before=Pt(0); p_note.paragraph_format.space_after=Pt(6)
    r_note=p_note.add_run("Complete the fields below. Both parties must fill in their information.")
    r_note.font.name=FN; r_note.font.size=Pt(9); r_note.font.color.rgb=GRAY; r_note.font.italic=True

    parties_table(doc,
        info['parties']['a_label'], info['parties']['b_label'],
        info['parties']['a_fields'], info['parties']['b_fields'])

    # Contract sections
    for item in info.get('sections',[]):
        t=item['type']
        if t=='h2': h2(doc,item['text'])
        elif t=='h3': h3(doc,item['text'])
        elif t=='body': body(doc,item['text'])
        elif t=='fill': fill_line(doc,item.get('label',''),item.get('chars',28))

    # Prohibited uses
    if info.get('prohibited'):
        h2(doc,"Prohibited Uses")
        p_pro=doc.add_paragraph()
        p_pro.paragraph_format.space_before=Pt(2); p_pro.paragraph_format.space_after=Pt(4)
        r_pro=p_pro.add_run("The Licensed Portrait may NOT be used for any of the following purposes:")
        r_pro.font.name=FN; r_pro.font.size=Pt(9.5); r_pro.font.color.rgb=GRAY; r_pro.font.italic=True
        for item in info['prohibited']: checkbox(doc,item)

    # Signatures
    h2(doc,"Signatures")
    p_sig=doc.add_paragraph()
    p_sig.paragraph_format.space_before=Pt(4); p_sig.paragraph_format.space_after=Pt(4)
    r_sig=p_sig.add_run("By signing below, both parties agree to all terms and conditions set forth in this Agreement.")
    r_sig.font.name=FN; r_sig.font.size=Pt(9.5); r_sig.font.color.rgb=GRAY; r_sig.font.italic=True
    sig_block(doc, info.get('sig_party_a','Party A'), info.get('sig_party_b','Party B'))

    add_url_bottom(doc)
    doc.save(info['output_path'])
    sz=os.path.getsize(info['output_path'])//1024
    print(f"[OK] {os.path.basename(info['output_path']):50s} ({sz} KB)")

# ─── Contract definitions ──────────────────────────────────────────────────────

CONTRACTS = [

    {
        'output_path': os.path.join(EN_DIR,"02-Exclusive-License-Agreement.docx"),
        'title': 'EXCLUSIVE LICENSE AGREEMENT',
        'subtitle': 'Exclusive Portrait Licensing Contract',
        'license_type': 'Exclusive',
        'price_range': 'USD 500 - 50,000',
        'parties': {
            'a_label': 'LICENSOR (Portrait Owner)',
            'b_label': 'LICENSEE (Authorized User)',
            'a_fields': ['Full Legal Name','Email Address','Mailing Address','Phone Number'],
            'b_fields': ['Full Legal Name / Company','Email Address','Company / Organization','Phone Number'],
        },
        'sections': [
            {'type':'h2','text':'1. Grant of Exclusive License'},
            {'type':'body','text':'The Licensor hereby grants to the Licensee an exclusive, non-transferable license to use the Licensor\'s digital portrait ("Licensed Portrait"). During the term of this Agreement, the Licensor shall not grant any other license to any third party for the Licensed Portrait, and agrees to cease all independent use of the Licensed Portrait worldwide.'},
            {'type':'h2','text':'2. Exclusivity Terms'},
            {'type':'body','text':'This exclusive license grants the Licensee sole rights to use, reproduce, distribute, publicly display, and create derivative works from the Licensed Portrait. The Licensor acknowledges that the exclusivity premium is reflected in the fee range above. Any use by the Licensor themselves during the license term is strictly prohibited.'},
            {'type':'h2','text':'3. Duration and Territory'},
            {'type':'body','text':'This exclusive license is granted for a period of one (1) to five (5) years from the date of digital execution, as agreed by both parties. The territory is worldwide unless otherwise specified in Appendix A.'},
            {'type':'fill','label':'License Start Date','chars':28},
            {'type':'fill','label':'License End Date','chars':28},
            {'type':'fill','label':'Exclusivity Term (Years)','chars':28},
            {'type':'fill','label':'Territory','chars':28},
            {'type':'h2','text':'4. Consideration and Payment'},
            {'type':'body','text':'The Licensee shall pay the Licensor an exclusivity premium fee as agreed during the digital signing process. PortraitPay AI will process the payment and transfer the net proceeds (after deducting the 1% platform fee) to the Licensor within five (5) business days of receipt.'},
            {'type':'fill','label':'Agreed License Fee (USD)','chars':28},
            {'type':'fill','label':'Payment Method','chars':28},
            {'type':'h2','text':'5. Representations and Warranties'},
            {'type':'body','text':'The Licensor represents and warrants that: (a) the Licensor is the sole and exclusive owner of the Licensed Portrait; (b) the Licensed Portrait does not infringe upon any third-party intellectual property rights; (c) the Licensor has obtained all necessary consents and model releases; (d) the Licensor will not negotiate any conflicting license during the term of this Agreement.'},
            {'type':'h2','text':'6. Infringement Assistance'},
            {'type':'body','text':'PortraitPay AI will assist in monitoring and enforcing this exclusive license against third-party infringement. The Licensor is entitled to complimentary legal consultation for any infringement case related to this Agreement through PortraitPay AI\'s partner lawyer network.'},
            {'type':'h2','text':'7. Limitation of Liability'},
            {'type':'body','text':'To the maximum extent permitted by applicable law, neither party shall be liable for any indirect, incidental, or consequential damages. The total aggregate liability shall not exceed the total license fees paid under this Agreement.'},
            {'type':'h2','text':'8. Governing Law'},
            {'type':'body','text':'This Agreement shall be governed by the laws of the State of California, USA. Disputes shall be subject to the exclusive jurisdiction of the courts of Los Angeles County, California.'},
            {'type':'h2','text':'9. Termination'},
            {'type':'body','text':'Termination may occur upon mutual written agreement or if either party materially breaches this Agreement and fails to cure within thirty (30) days of notice. Upon termination, all exclusive rights revert to the Licensor and the Licensee must cease all use immediately.'},
        ],
        'prohibited': [
            'Use by the Licensor themselves during the exclusivity term',
            'Any sublicensing or transfer of this exclusive license',
            'Adult, pornographic, or sexually explicit content',
            'Political, extremist, or propaganda content',
            'Violent, gory, or graphic content',
            'Hateful, discriminatory, or defamatory content',
            'Fraudulent, scam, or deceptive content',
            'Illegal activities or unlawful purposes',
        ],
        'sig_party_a': 'Licensor',
        'sig_party_b': 'Licensee',
    },

    {
        'output_path': os.path.join(EN_DIR,"03-Endorsement-License-Agreement.docx"),
        'title': 'ENDORSEMENT LICENSE AGREEMENT',
        'subtitle': 'Brand Ambassador Portrait Licensing Contract',
        'license_type': 'Endorsement',
        'price_range': 'USD 1,000 - 100,000',
        'parties': {
            'a_label': 'ENDORSER (Portrait Owner)',
            'b_label': 'BRAND (Authorized User)',
            'a_fields': ['Full Legal Name','Email Address','Mailing Address','Phone Number'],
            'b_fields': ['Company / Brand Name','Contact Email','Registered Address','Brand Website'],
        },
        'sections': [
            {'type':'h2','text':'1. Grant of Endorsement License'},
            {'type':'body','text':'The Endorser hereby grants the Brand a license to use the Endorser\'s digital portrait, name, likeness, and voice (if applicable) ("Endorsed Portrait") for the purpose of authentic brand endorsement and promotion. This license is non-exclusive but excludes use by direct competitors of the Brand during the endorsement term.'},
            {'type':'h2','text':'2. Scope of Endorsement'},
            {'type':'body','text':'The Brand is authorized to use the Endorsed Portrait in: advertising campaigns across all media; product packaging and labeling; social media posts and paid promotions; press releases and public announcements; point-of-sale and retail materials. Face verification at mint time is required to ensure authenticity of the digital portrait.'},
            {'type':'h2','text':'3. Exclusivity and Conflict'},
            {'type':'body','text':'During the endorsement term, the Endorser agrees not to endorse any competing brand in the same product category. Specific competitor brands are listed in Appendix A. The Brand agrees not to use the Endorsed Portrait in any context that contradicts the Endorser\'s publicly stated values or beliefs.'},
            {'type':'fill','label':'Endorsement Start Date','chars':28},
            {'type':'fill','label':'Endorsement End Date','chars':28},
            {'type':'fill','label':'Product Category','chars':28},
            {'type':'fill','label':'Exclusivity Territory','chars':28},
            {'type':'h2','text':'4. Consideration and Revenue Share'},
            {'type':'body','text':'The Brand shall pay the Endorser a licensing fee and/or revenue share as agreed during the digital signing process. PortraitPay AI will process payments and distribute net proceeds (after deducting the 1% platform fee) according to the schedule specified in Appendix B.'},
            {'type':'fill','label':'Fixed License Fee (USD)','chars':28},
            {'type':'fill','label':'Revenue Share (%)','chars':28},
            {'type':'fill','label':'Payment Schedule','chars':28},
            {'type':'h2','text':'5. Representations and Warranties'},
            {'type':'body','text':'The Endorser represents and warrants that: (a) the Endorser has full legal capacity to enter into this endorsement Agreement; (b) the Endorsed Portrait is original and does not infringe third-party rights; (c) the Endorser has not granted conflicting endorsement rights to any competitor.'},
            {'type':'h2','text':'6. Content Approval'},
            {'type':'body','text':'The Brand shall submit all proposed uses of the Endorsed Portrait to the Endorser for written approval prior to publication. The Endorser shall respond within five (5) business days of receipt. Unapproved uses constitute a material breach of this Agreement.'},
            {'type':'h2','text':'7. Termination for Misuse'},
            {'type':'body','text':'The Endorser may terminate this Agreement immediately upon written notice if the Brand uses the Endorsed Portrait in a manner that: brings the Endorser into public disrepute; violates any law or regulation; is associated with illegal products or services; or breaches the content approval requirements.'},
            {'type':'h2','text':'8. Governing Law'},
            {'type':'body','text':'This Agreement shall be governed by the laws of the State of California, USA. Any disputes shall be subject to the exclusive jurisdiction of the courts of Los Angeles County, California.'},
        ],
        'prohibited': [
            'Association with competitors in the same product category',
            'Political, extremist, or controversial causes',
            'Adult, pornographic, or sexually explicit content',
            'Violent, gory, or graphic content',
            'Fraudulent, scam, or deceptive advertising',
            'Products or services that are illegal in the territory',
            'Misrepresentation of the Endorser\'s affiliation or values',
        ],
        'sig_party_a': 'Endorser',
        'sig_party_b': 'Brand',
    },

    {
        'output_path': os.path.join(EN_DIR,"04-Film-Adaptation-License-Agreement.docx"),
        'title': 'FILM ADAPTATION LICENSE AGREEMENT',
        'subtitle': 'Content Adaptation Portrait Licensing Contract',
        'license_type': 'Film / Content Adaptation',
        'price_range': 'USD 5,000 - 500,000',
        'parties': {
            'a_label': 'LICENSOR (Portrait Owner)',
            'b_label': 'PRODUCER (Content User)',
            'a_fields': ['Full Legal Name / Stage Name','Email Address','Mailing Address','Phone Number'],
            'b_fields': ['Production Company Name','Contact Email','Production Address','Project Title'],
        },
        'sections': [
            {'type':'h2','text':'1. Grant of Adaptation License'},
            {'type':'body','text':'The Licensor hereby grants the Producer a non-exclusive license to use the Licensor\'s digital portrait ("Licensed Portrait") in connection with the production, distribution, promotion, and exploitation of a film, television, or digital content project ("the Project"). This license includes the right to reproduce, distribute, publicly display, and create derivative works incorporating the Licensed Portrait.'},
            {'type':'h2','text':'2. Project Scope'},
            {'type':'body','text':'The Producer is authorized to use the Licensed Portrait in: film trailers and theatrical posters; television broadcast and streaming promotion; digital advertising campaigns; merchandise and packaging related to the Project; press and media materials. Face verification at mint time is required to ensure authenticity of the Licensed Portrait.'},
            {'type':'fill','label':'Project Title','chars':28},
            {'type':'fill','label':'Project Type (Film/TV/Web)','chars':28},
            {'type':'fill','label':'License Start Date','chars':28},
            {'type':'fill','label':'License End Date','chars':28},
            {'type':'fill','label':'Distribution Territory','chars':28},
            {'type':'fill','label':'Exhibition Platform(s)','chars':28},
            {'type':'h2','text':'3. Revenue Sharing'},
            {'type':'body','text':'In consideration for the license granted herein, the Producer shall pay the Licensor a combination of an upfront advance against royalties and an ongoing revenue share based on the Project\'s commercial performance. Revenue splits are defined in Appendix A. PortraitPay AI will process payments through its smart contract system, automatically distributing net proceeds after deducting the 1% platform fee.'},
            {'type':'fill','label':'Advance Payment (USD)','chars':28},
            {'type':'fill','label':'Royalty Rate (%)','chars':28},
            {'type':'fill','label':'Revenue Reporting Frequency','chars':28},
            {'type':'h2','text':'4. Lawyer Review Requirement'},
            {'type':'body','text':'Due to the complexity and value of film adaptation licenses, both parties acknowledge that this Agreement has been reviewed or may be reviewed by a qualified attorney prior to execution. PortraitPay AI can facilitate the connection to its partner lawyer network for both parties.'},
            {'type':'h2','text':'5. Credit and Attribution'},
            {'type':'body','text':'The Producer agrees to provide appropriate credit to the Licensor in all credits and attribution materials for the Project, in the form: "Portrait courtesy of [Full Legal Name] — PortraitPay AI". The form and placement of credit shall be agreed upon in writing before the Project\'s public release.'},
            {'type':'h2','text':'6. Representations and Warranties'},
            {'type':'body','text':'The Licensor represents and warrants that: (a) the Licensed Portrait is original and the Licensor has full authority to grant this license; (b) the Licensed Portrait does not infringe any third-party intellectual property or privacy rights; (c) the Licensor has obtained all necessary model releases. The Producer represents that the Project will comply with all applicable laws and regulations.'},
            {'type':'h2','text':'7. Governing Law'},
            {'type':'body','text':'This Agreement shall be governed by the laws of the State of California, USA. Any disputes shall be subject to the exclusive jurisdiction of the courts of Los Angeles County, California.'},
            {'type':'h2','text':'8. Termination'},
            {'type':'body','text':'Either party may terminate upon sixty (60) days written notice. Upon termination, the Producer must cease all new use of the Licensed Portrait and remove all existing uses from circulation within thirty (30) days, except for materials already distributed and for which recall is commercially impractical.'},
        ],
        'prohibited': [
            'Use in content that is pornographic, obscene, or defamatory',
            'Use in connection with illegal products, services, or activities',
            'Association with political extremist or hate group content',
            'Modification of the Licensed Portrait beyond agreed adaptation scope',
            'Transfer of this license to a third party without written consent',
            'Use in competing film or content projects during the license term',
        ],
        'sig_party_a': 'Licensor',
        'sig_party_b': 'Producer',
    },

    {
        'output_path': os.path.join(EN_DIR,"00-Overview-and-Signing-Guide.docx"),
        'title': 'PORTRAITPAY AI CONTRACT GUIDE',
        'subtitle': 'Overview and Signing Instructions',
        'license_type': 'All Contract Types',
        'price_range': 'See Individual Contracts',
        'parties': {
            'a_label': 'PARTY A (Portrait Owner)',
            'b_label': 'PARTY B (Authorized User)',
            'a_fields': ['Full Legal Name','Email Address','Mailing Address','Phone Number'],
            'b_fields': ['Full Legal Name / Company','Email Address','Company / Organization','Phone Number'],
        },
        'sections': [
            {'type':'h2','text':'About PortraitPay AI'},
            {'type':'body','text':'PortraitPay AI is a blockchain-based portrait rights management platform. Every portrait is stored on-chain with an immutable timestamp, creating a legally recognized certificate of ownership. When you sign a digital licensing contract through PortraitPay AI, the agreement is recorded on the blockchain and stored on IPFS, providing tamper-proof evidence of the licensing relationship.'},
            {'type':'h2','text':'Four Contract Types Available'},
            {'type':'body','text':'PortraitPay AI offers four specialized digital human licensing contracts, each designed for a different use case:\n\n1. STANDARD (Non-Exclusive): For general commercial and personal use. Fee range: USD 100 - 10,000. Platform fee: 1%.\n\n2. EXCLUSIVE: For situations requiring sole rights. Fee range: USD 500 - 50,000. Includes complimentary legal consultation through our partner lawyer network.\n\n3. ENDORSEMENT: For brand ambassador and celebrity endorsement relationships. Fee range: USD 1,000 - 100,000. Includes face verification at mint time.\n\n4. FILM ADAPTATION: For film, television, and content production use. Fee range: USD 5,000 - 500,000. Includes smart contract auto-split revenue sharing.'},
            {'type':'h2','text':'How to Sign a Contract'},
            {'type':'body','text':'Step 1 — Register: Create a free account at portraitpayai.com and complete your profile.\n\nStep 2 — Upload Portrait: Upload a clear, high-resolution portrait photo. The system will generate a 128-dimensional face vector stored in our database and a SHA-256 hash recorded on the Base blockchain.\n\nStep 3 — Select Contract Type: Choose the contract type that matches your intended use. Each contract clearly states the license scope, fee range, and permitted uses.\n\nStep 4 — Face Verification: For Endorsement and Film Adaptation contracts, face verification is required at mint time to ensure authenticity.\n\nStep 5 — Digital Signing: Both parties review the contract terms and sign digitally through the PortraitPay AI platform.\n\nStep 6 — Payment: The Licensee pays the agreed fee. PortraitPay AI deducts the 1% platform fee and transfers the remainder to the Licensor within 5 business days.'},
            {'type':'h2','text':'Important Legal Notes'},
            {'type':'body','text':'All contracts are governed by the laws of the State of California, USA. Disputes fall under the exclusive jurisdiction of Los Angeles County courts.\n\nFace verification at mint time ensures that the person signing is the legitimate owner of the portrait. This creates a strong chain of evidence if disputes ever arise.\n\nAll contract data is stored on IPFS (InterPlanetary File System) with a content hash recorded on the Base blockchain. This provides legal-grade evidence that can be used in court proceedings.\n\nPortraitPay AI charges a flat 1% platform fee on all transactions. No hidden fees. No recurring charges.'},
            {'type':'h2','text':'Dispute Resolution'},
            {'type':'body','text':'If a dispute arises under any PortraitPay AI contract, both parties agree to first attempt resolution through our partner lawyer network mediation process. If mediation fails, disputes shall be submitted to binding arbitration in Los Angeles County, California, under the rules of the American Arbitration Association.'},
        ],
        'prohibited': [
            'PortraitPay AI contracts do not grant indefinite perpetual rights',
            'All contracts have a defined term — please check each contract for duration',
            'PortraitPay AI reserves the right to terminate accounts that violate the prohibited use provisions',
            'Misuse of the platform for illegal purposes will be reported to authorities',
        ],
        'sig_party_a': 'Party A',
        'sig_party_b': 'Party B',
    },
]

# ─── Run ──────────────────────────────────────────────────────────────────────
os.makedirs(EN_DIR, exist_ok=True)
print("Generating 4 contracts in finalized style...")
print()
for c in CONTRACTS:
    build(Document(), c)
print()
print("All done. Open each file to verify before sharing.")