"""
PortraitPay AI — Contract Templates v5
Navy blue color scheme, header-first-page-only, footer-last-page-only
"""
import os, re, copy
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm, Twips
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

LOGO_PATH = r"I:\Portraitpay ai\Logo 设计\PortraitpayAI.png"
BRAND_TEXT = "This template was generated by PortraitPay AI"
EN_DIR     = r"I:\Portraitpay ai\Doc\合同模板设计\EN"

# Navy blue palette (from lawyer-registration page)
NAVY    = RGBColor(0x24, 0x41, 0x69)
NAVY2   = RGBColor(0x1E, 0x4A, 0x7B)
WHITE   = RGBColor(0xFF, 0xFF, 0xFF)
GRAY    = RGBColor(0x60, 0x60, 0x60)
BLACK   = RGBColor(0x1A, 0x1A, 0x1A)
FN      = "Arial"

# ─── Helpers ──────────────────────────────────────────────────────────────────

def rgb_hex(r, g, b):
    return RGBColor(r, g, b)

def shd(cell, fill_hex):
    tc=cell._tc; tp=tc.get_or_add_tcPr()
    s=OxmlElement('w:shd')
    s.set(qn('w:val'),'clear'); s.set(qn('w:color'),'auto')
    s.set(qn('w:fill'), fill_hex); tp.append(s)

def cell_borders(cell, c="CCCCCC", sz="4"):
    tc=cell._tc; tp=tc.get_or_add_tcPr()
    b=OxmlElement('w:tcBorders')
    for e in ('top','left','bottom','right'):
        x=OxmlElement(f'w:{e}'); x.set(qn('w:val'),'single')
        x.set(qn('w:sz'),sz); x.set(qn('w:space'),'0'); x.set(qn('w:color'),c)
        b.append(x)
    tp.append(b)

def tbl_no_borders(tbl):
    tp=tbl._tbl.tblPr; tb=OxmlElement('w:tblBorders')
    for e in ('top','left','bottom','right','insideH','insideV'):
        x=OxmlElement(f'w:{e}'); x.set(qn('w:val'),'none')
        x.set(qn('w:sz'),'0'); x.set(qn('w:space'),'0'); x.set(qn('w:color'),'auto')
        tb.append(x)
    tp.append(tb)

def vcenter(cell):
    tc=cell._tc; tp=tc.get_or_add_tcPr()
    v=OxmlElement('w:vAlign'); v.set(qn('w:val'),'center'); tp.append(v)

def jc_center(cell):
    tc=cell._tc; tp=tc.get_or_add_tcPr()
    jc=OxmlElement('w:jc'); jc.set(qn('w:val'),'center'); tp.append(jc)

def para_border_bottom(para, c="244169", sz="6"):
    pPr=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single')
    b.set(qn('w:sz'),sz); b.set(qn('w:space'),'1'); b.set(qn('w:color'),c)
    pb.append(b); pPr.append(pb)

def para_border_top(para, c="CCCCCC", sz="4"):
    pPr=para._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    t=OxmlElement('w:top'); t.set(qn('w:val'),'single')
    t.set(qn('w:sz'),sz); t.set(qn('w:space'),'1'); t.set(qn('w:color'),c)
    pb.append(t); pPr.append(pb)

def add_page_field(para, label, fname):
    r=para.add_run(label)
    r.font.size=Pt(8.5); r.font.color.rgb=WHITE; r.font.name=FN
    r2=para.add_run()
    r2.font.size=Pt(8.5); r2.font.color.rgb=WHITE; r2.font.name=FN
    fb=OxmlElement('w:fldChar'); fb.set(qn('w:fldCharType'),'begin')
    ins=OxmlElement('w:instrText'); ins.text=fname
    fe=OxmlElement('w:fldChar'); fe.set(qn('w:fldCharType'),'end')
    r2._r.append(fb); r2._r.append(ins); r2._r.append(fe)

def sect_first_page_header(doc, body_para):
    """Add 'first page' header: only appears on page 1"""
    section = doc.sections[-1]
    header  = section.header
    for p in header.paragraphs: p.clear()

    tbl=header.add_table(1,3,width=Inches(6.5))
    tbl_no_borders(tbl)
    tbl.alignment=WD_TABLE_ALIGNMENT.CENTER

    for col in tbl.columns:
        for cell in col.cells: cell.width=Inches(6.5/3)

    # Center cell: logo + text
    cc=tbl.cell(0,1)
    jc_center(cc); vcenter(cc)
    cp=cc.paragraphs[0]
    cp.alignment=WD_ALIGN_PARAGRAPH.CENTER
    cp.paragraph_format.space_before=Pt(6); cp.paragraph_format.space_after=Pt(6)
    r_img=cp.add_run()
    r_img.add_picture(LOGO_PATH, width=Inches(0.55))
    r_txt=cp.add_run("  " + BRAND_TEXT)
    r_txt.font.size=Pt(9); r_txt.font.color.rgb=WHITE; r_txt.font.name=FN

    # Navy bottom border
    pPr=header.paragraphs[0]._p.get_or_add_pPr()
    pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single')
    b.set(qn('w:sz'),'8'); b.set(qn('w:space'),'1'); b.set(qn('w:color'),'244169')
    pb.append(b); pPr.append(pb)

def sect_white_footer_last_page(doc):
    """Add footer that only shows on last page"""
    section = doc.sections[-1]
    footer   = section.footer
    for p in footer.paragraphs: p.clear()

    tbl=footer.add_table(1,3,width=Inches(6.5))
    tbl_no_borders(tbl); tbl.alignment=WD_TABLE_ALIGNMENT.CENTER

    for col in tbl.columns:
        for cell in col.cells: cell.width=Inches(6.5/3)

    # Navy top border
    pPr=footer.paragraphs[0]._p.get_or_add_pPr()
    pb=OxmlElement('w:pBdr')
    t=OxmlElement('w:top'); t.set(qn('w:val'),'single')
    t.set(qn('w:sz'),'8'); t.set(qn('w:space'),'1'); t.set(qn('w:color'),'244169')
    pb.append(t); pPr.append(pb)

    # Center: URL
    c0=tbl.cell(0,0); vcenter(c0)
    p0=c0.paragraphs[0]; p0.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p0.paragraph_format.space_before=Pt(6)
    r0=p0.add_run("portraitpayai.com/")
    r0.font.size=Pt(8.5); r0.font.color.rgb=WHITE; r0.font.name=FN

    # Center cell: page number
    c1=tbl.cell(0,1); vcenter(c1)
    p1=c1.paragraphs[0]; p1.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p1.paragraph_format.space_before=Pt(6)
    add_page_field(p1,"Page ","PAGE")
    r_of=p1.add_run(" of "); r_of.font.size=Pt(8.5); r_of.font.color.rgb=WHITE; r_of.font.name=FN
    add_page_field(p1,"","NUMPAGES")

    c2=tbl.cell(0,2); vcenter(c2)

    # Apply navy background to entire footer paragraph
    pPr2=footer.paragraphs[0]._p.get_or_add_pPr()
    shd2=OxmlElement('w:shd')
    shd2.set(qn('w:val'),'clear'); shd2.set(qn('w:color'),'auto')
    shd2.set(qn('w:fill'),'244169'); pPr2.append(shd2)

def add_section_break_next_page(doc):
    """Insert continuous section break so header/footer can be set per-section"""
    p=doc.add_paragraph()
    pPr=p._p.get_or_add_pPr()
    sectPr=OxmlElement('w:sectPr')
    # Mark this as the end of the previous section
    pgSz=OxmlElement('w:pgSz')
    pgSz.set(qn('w:w'),'12240'); pgSz.set(qn('w:h'),'15840')
    sectPr.append(pgSz)
    pgMar=OxmlElement('w:pgMar')
    pgMar.set(qn('w:top'),'1440'); pgMar.set(qn('w:right'),'1440')
    pgMar.set(qn('w:bottom'),'1440'); pgMar.set(qn('w:left'),'1440')
    pgMar.set(qn('w:header'),'720'); pgMar.set(qn('w:footer'),'720')
    pgMar.set(qn('w:gutter'),'0')
    sectPr.append(pgMar)
    pPr.append(sectPr)
    return p

# ─── Content builders ──────────────────────────────────────────────────────────

def h2(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(14); p.paragraph_format.space_after=Pt(3)
    r=p.add_run(text.upper())
    r.font.name=FN; r.font.size=Pt(11); r.font.bold=True; r.font.color.rgb=NAVY
    para_border_bottom(p, c="244169", sz="6")

def h3(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(8); p.paragraph_format.space_after=Pt(2)
    r=p.add_run(text)
    r.font.name=FN; r.font.size=Pt(10.5); r.font.bold=True; r.font.color.rgb=BLACK

def body(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(4); p.paragraph_format.space_after=Pt(6)
    for pi,pt in enumerate(re.split(r'\*\*(.*?)\*\*',text)):
        r=p.add_run(pt); r.font.name=FN; r.font.size=Pt(10.5); r.font.color.rgb=BLACK
        if pi%2==1: r.font.bold=True

def fill_line(doc, label, chars=30):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(3); p.paragraph_format.space_after=Pt(3)
    if label:
        r1=p.add_run(label+":  "); r1.font.name=FN; r1.font.size=Pt(9.5); r1.font.color.rgb=GRAY
    r2=p.add_run("_"*chars); r2.font.name=FN; r2.font.size=Pt(9.5); r2.font.color.rgb=BLACK

def checkbox(doc, text):
    p=doc.add_paragraph()
    p.paragraph_format.space_before=Pt(2); p.paragraph_format.space_after=Pt(2)
    p.paragraph_format.left_indent=Inches(0.25)
    r=p.add_run("\u2610  "+text); r.font.name=FN; r.font.size=Pt(10); r.font.color.rgb=BLACK

def parties_table(doc, a_label, b_label, a_fields, b_fields):
    tbl=doc.add_table(rows=2+len(a_fields), cols=2)
    tbl.style='Table Grid'; tbl.alignment=WD_TABLE_ALIGNMENT.LEFT
    for ci,w in enumerate([Inches(3.0),Inches(3.0)]):
        for cell in tbl.columns[ci].cells: cell.width=w

    # Header
    for ci,hdr_text in enumerate([a_label, b_label]):
        cell=tbl.rows[0].cells[ci]; cell.text=""
        pp=cell.paragraphs[0]
        pp.paragraph_format.space_before=Pt(5); pp.paragraph_format.space_after=Pt(5)
        rr=pp.add_run(hdr_text); rr.font.name=FN; rr.font.size=Pt(10); rr.font.bold=True
        rr.font.color.rgb=WHITE; shd(cell,"244169"); cell_borders(cell,"1A1A1A","4")

    for ri,(fa,fb) in enumerate(zip(a_fields,b_fields)):
        row=tbl.rows[ri+1]; row.height=Twips(400)
        for ci,(cell,lbl) in enumerate(zip(row.cells,[fa,fb])):
            cell.text=""; pp=cell.paragraphs[0]
            pp.paragraph_format.space_before=Pt(5); pp.paragraph_format.space_after=Pt(5)
            r1=pp.add_run(lbl+":  "); r1.font.name=FN; r1.font.size=Pt(9.5); r1.font.color.rgb=GRAY
            r2=pp.add_run("_"*25); r2.font.name=FN; r2.font.size=Pt(9.5); r2.font.color.rgb=NAVY
            shd(cell,"F0F4FA"); cell_borders(cell,"D0D8E8","4")

    sp=doc.add_paragraph(); sp.paragraph_format.space_after=Pt(8)

def license_box(doc, lic_type, price_range):
    tbl=doc.add_table(rows=1,cols=1)
    tbl.alignment=WD_TABLE_ALIGNMENT.CENTER; tbl.style='Table Grid'
    cell=tbl.rows[0].cells[0]; cell.text=""
    pp=cell.paragraphs[0]; pp.alignment=WD_ALIGN_PARAGRAPH.CENTER
    pp.paragraph_format.space_before=Pt(8); pp.paragraph_format.space_after=Pt(8)
    rr=pp.add_run(f"LICENSE TYPE:  {lic_type}    |    FEE RANGE:  {price_range}")
    rr.font.name=FN; rr.font.size=Pt(11); rr.font.bold=True; rr.font.color.rgb=WHITE
    shd(cell,"244169"); cell_borders(cell,"1A1A1A","4")
    sp=doc.add_paragraph(); sp.paragraph_format.space_after=Pt(10)

def sig_block(doc, party_a, party_b):
    labels=["Signature","Print Name","Date"]
    tbl=doc.add_table(rows=3,cols=2); tbl_no_borders(tbl)
    tbl.alignment=WD_TABLE_ALIGNMENT.LEFT
    for ri,la in enumerate(labels):
        row=tbl.rows[ri]
        for ci,(cell,lbl) in enumerate(zip(row.cells,[party_a,party_b])):
            cell.text=""; pp=cell.paragraphs[0]
            pp.paragraph_format.space_before=Pt(3); pp.paragraph_format.space_after=Pt(2)
            r1=pp.add_run(lbl+" "+la+":  ")
            r1.font.name=FN; r1.font.size=Pt(9.5); r1.font.color.rgb=GRAY
            r2=pp.add_run("_"*35)
            r2.font.name=FN; r2.font.size=Pt(9.5); r2.font.color.rgb=NAVY
    sp=doc.add_paragraph(); sp.paragraph_format.space_after=Pt(4)

def build_contract(doc, info, is_first_contract=False):
    sty=doc.styles['Normal']; sty.font.name=FN; sty.font.size=Pt(10.5)
    sec=doc.sections[-1]
    sec.top_margin=Cm(2.2); sec.bottom_margin=Cm(2.2)
    sec.left_margin=Cm(2.5); sec.right_margin=Cm(2.5)

    # ── Header (first page only) ──
    sect_first_page_header(doc, None)

    # ── Title ──
    p=doc.add_paragraph()
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(4); p.paragraph_format.space_after=Pt(6)
    r=p.add_run(info['title']); r.font.name=FN; r.font.size=Pt(22); r.font.bold=True
    r.font.color.rgb=NAVY

    if info.get('subtitle'):
        p2=doc.add_paragraph()
        p2.alignment=WD_ALIGN_PARAGRAPH.CENTER
        p2.paragraph_format.space_before=Pt(0); p2.paragraph_format.space_after=Pt(12)
        r2=p2.add_run(info['subtitle'])
        r2.font.name=FN; r2.font.size=Pt(11); r2.font.color.rgb=GRAY

    license_box(doc, info.get('license_type',''), info.get('price_range',''))

    # Parties
    p_hdr=doc.add_paragraph()
    p_hdr.paragraph_format.space_before=Pt(8); p_hdr.paragraph_format.space_after=Pt(4)
    r_hdr=p_hdr.add_run("PARTIES TO THIS AGREEMENT")
    r_hdr.font.name=FN; r_hdr.font.size=Pt(10.5); r_hdr.font.bold=True; r_hdr.font.color.rgb=NAVY
    para_border_bottom(p_hdr, c="244169", sz="4")

    p_note=doc.add_paragraph()
    p_note.paragraph_format.space_before=Pt(2); p_note.paragraph_format.space_after=Pt(6)
    r_note=p_note.add_run("Complete the fields below. Both parties must fill in their information.")
    r_note.font.name=FN; r_note.font.size=Pt(9); r_note.font.color.rgb=GRAY; r_note.font.italic=True

    parties_table(doc,
        info['parties']['a_label'], info['parties']['b_label'],
        info['parties']['a_fields'], info['parties']['b_fields'])

    # ── Sections ──
    for item in info.get('sections',[]):
        t=item['type']
        if t=='h2': h2(doc, item['text'])
        elif t=='h3': h3(doc, item['text'])
        elif t=='body': body(doc, item['text'])
        elif t=='fill': fill_line(doc, item.get('label',''), item.get('chars',30))

    # Prohibited uses
    if info.get('prohibited'):
        h2(doc, "Prohibited Uses")
        p_pro=doc.add_paragraph()
        p_pro.paragraph_format.space_before=Pt(2); p_pro.paragraph_format.space_after=Pt(4)
        r_pro=p_pro.add_run("The Licensed Portrait may NOT be used for any of the following purposes:")
        r_pro.font.name=FN; r_pro.font.size=Pt(9.5); r_pro.font.color.rgb=GRAY; r_pro.font.italic=True
        for item in info['prohibited']: checkbox(doc, item)

    # Signatures
    h2(doc, "Signatures")
    p_sig=doc.add_paragraph()
    p_sig.paragraph_format.space_before=Pt(4); p_sig.paragraph_format.space_after=Pt(4)
    r_sig=p_sig.add_run("By signing below, both parties agree to all terms and conditions set forth in this Agreement.")
    r_sig.font.name=FN; r_sig.font.size=Pt(9.5); r_sig.font.color.rgb=GRAY; r_sig.font.italic=True
    sig_block(doc, info.get('sig_party_a','Party A'), info.get('sig_party_b','Party B'))

    # ── Section break → last-page-only footer ──
    # Insert a "next page" section so the last section has the footer
    add_section_break_next_page(doc)

    # Now set footer on the final section (last page only)
    sect_white_footer_last_page(doc)

    doc.save(info['output_path'])
    sz=os.path.getsize(info['output_path'])//1024
    print(f"[OK] {os.path.basename(info['output_path']):55s} ({sz} KB)")

# ─── Contract data ─────────────────────────────────────────────────────────────

STANDARD = {
    'title':'STANDARD LICENSE AGREEMENT',
    'subtitle':'Non-Exclusive Portrait Licensing Contract',
    'license_type':'Standard (Non-Exclusive)',
    'price_range':'USD 100 - 10,000',
    'parties':{
        'a_label':'LICENSOR (Portrait Owner)',
        'b_label':'LICENSEE (Authorized User)',
        'a_fields':['Full Legal Name','Email Address','Mailing Address','Phone Number'],
        'b_fields':['Full Legal Name / Company','Email Address','Company / Organization','Phone Number'],
    },
    'sections':[
        {'type':'h2','text':'1. Grant of License'},
        {'type':'body','text':'The Licensor hereby grants to the Licensee a non-exclusive, non-transferable license to use the Licensor\'s digital portrait ("Licensed Portrait") for the purposes described in this Agreement. This license is limited to the specific uses selected by the Licensee during the digital signing process on the PortraitPay AI platform at https://portraitpayai.com/.'},
        {'type':'h2','text':'2. License Scope and Permitted Uses'},
        {'type':'body','text':'Subject to the terms of this Agreement, the Licensee is authorized to use the Licensed Portrait solely for: advertising, marketing, and promotional materials; product packaging and labeling; social media content; digital and print publications; and other uses as agreed in writing.'},
        {'type':'h2','text':'3. Territory and Duration'},
        {'type':'body','text':'This license is granted for a period of one (1) year from the date of digital execution unless earlier terminated. The territory is worldwide (global) unless otherwise specified.'},
        {'type':'fill','label':'License Start Date','chars':28},
        {'type':'fill','label':'License End Date','chars':28},
        {'type':'fill','label':'Territory','chars':28},
        {'type':'h2','text':'4. Consideration and Payment'},
        {'type':'body','text':'The Licensee shall pay the Licensor a one-time licensing fee as agreed during the digital signing process. PortraitPay AI will process the payment and transfer the net proceeds (after deducting the 1% platform fee) to the Licensor within five (5) business days of receipt.'},
        {'type':'fill','label':'Agreed License Fee (USD)','chars':28},
        {'type':'fill','label':'Payment Method','chars':28},
        {'type':'h2','text':'5. Representations and Warranties'},
        {'type':'body','text':'The Licensor represents and warrants that: (a) the Licensor is the sole and exclusive owner of the Licensed Portrait and has full authority to grant this license; (b) the Licensed Portrait does not infringe upon any third-party intellectual property rights; (c) the Licensor has obtained all necessary consents for the creation and use of the Licensed Portrait.'},
        {'type':'h2','text':'6. Limitation of Liability'},
        {'type':'body','text':'To the maximum extent permitted by applicable law, neither party shall be liable for any indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with this Agreement. The total aggregate liability of either party shall not exceed the total license fees paid hereunder.'},
        {'type':'h2','text':'7. Governing Law'},
        {'type':'body','text':'This Agreement shall be governed by and construed in accordance with the laws of the State of California, United States of America, without regard to its conflict of law provisions. Any disputes shall be subject to the exclusive jurisdiction of the courts located in Los Angeles County, California.'},
        {'type':'h2','text':'8. Entire Agreement and Amendments'},
        {'type':'body','text':'This Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof. Any amendment or modification must be in writing and signed by both parties or executed digitally through the PortraitPay AI platform.'},
        {'type':'h2','text':'9. Termination'},
        {'type':'body','text':'Either party may terminate this Agreement upon thirty (30) days written notice. Upon termination, the Licensee must cease all use of the Licensed Portrait and remove all copies from circulation within five (5) business days. PortraitPay AI reserves the right to terminate this Agreement immediately for any material breach.'},
    ],
    'prohibited':[
        'Adult, pornographic, or sexually explicit content',
        'Political, extremist, or propaganda content',
        'Violent, gory, or graphic content',
        'Hateful, discriminatory, or defamatory content',
        'Fraudulent, scam, or deceptive content',
        'Sale of weapons or dangerous goods',
        'Illegal activities or unlawful purposes',
    ],
    'sig_party_a':'Licensor',
    'sig_party_b':'Licensee',
}

os.makedirs(EN_DIR, exist_ok=True)
STANDARD['output_path']=os.path.join(EN_DIR,"01-Standard-License-Agreement.docx")
build_contract(Document(), STANDARD, is_first_contract=True)
print("\nDone.")