"""Patch 01-Standard: add brand text to header/footer/body start, URL at last page bottom"""
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

LOGO_PATH = r"I:\Portraitpay ai\Logo 设计\PortraitpayAI.png"
BRAND_TEXT = "This template was generated by PortraitPay AI"
BRAND_URL  = "portraitpayai.com"
EN_DIR     = r"I:\Portraitpay ai\Doc\合同模板设计\EN"
DOCX_PATH  = os.path.join(EN_DIR, "01-Standard-License-Agreement.docx")

NAVY  = RGBColor(0x24,0x41,0x69)
WHITE = RGBColor(0xFF,0xFF,0xFF)
GRAY  = RGBColor(0x60,0x60,0x60)
FN    = "Arial"

def shd_para(para, fill_hex):
    pPr=para._p.get_or_add_pPr()
    s=OxmlElement('w:shd')
    s.set(qn('w:val'),'clear'); s.set(qn('w:color'),'auto')
    s.set(qn('w:fill'),fill_hex); pPr.append(s)

def cell_no_borders(cell):
    tc=cell._tc; tp=tc.get_or_add_tcPr()
    b=OxmlElement('w:tcBorders')
    for e in ('top','left','bottom','right'):
        x=OxmlElement(f'w:{e}'); x.set(qn('w:val'),'none')
        x.set(qn('w:sz'),'0'); x.set(qn('w:space'),'0'); x.set(qn('w:color'),'auto')
        b.append(x)
    tp.append(b)

def vcenter(cell):
    tc=cell._tc; tp=tc.get_or_add_tcPr()
    v=OxmlElement('w:vAlign'); v.set(qn('w:val'),'center'); tp.append(v)

def set_header(doc, text):
    """Set plain text header (centered), no background"""
    sec=doc.sections[0]; hdr=sec.header
    for p in hdr.paragraphs: p.clear()
    p=hdr.paragraphs[0]
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(6)
    p.paragraph_format.space_after=Pt(6)
    # Logo + text
    r_img=p.add_run()
    r_img.add_picture(LOGO_PATH, width=Inches(0.5))
    r=p.add_run("  " + text)
    r.font.name=FN; r.font.size=Pt(9); r.font.color.rgb=NAVY
    # Thin navy border bottom
    pPr=p._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single')
    b.set(qn('w:sz'),'4'); b.set(qn('w:space'),'1'); b.set(qn('w:color'),'244169')
    pb.append(b); pPr.append(pb)

def set_footer(doc, text):
    """Set plain text footer (centered), no background"""
    sec=doc.sections[0]; ftr=sec.footer
    for p in ftr.paragraphs: p.clear()
    p=ftr.paragraphs[0]
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(6)
    p.paragraph_format.space_after=Pt(6)
    r=p.add_run(text + "  |  ")
    r.font.name=FN; r.font.size=Pt(8.5); r.font.color.rgb=NAVY
    r2=p.add_run(BRAND_URL)
    r2.font.name=FN; r2.font.size=Pt(8.5); r2.font.color.rgb=NAVY
    # Thin navy border top
    pPr=p._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    t=OxmlElement('w:top'); t.set(qn('w:val'),'single')
    t.set(qn('w:sz'),'4'); t.set(qn('w:space'),'1'); t.set(qn('w:color'),'244169')
    pb.append(t); pPr.append(pb)

def add_url_last_page(doc, url):
    """Add URL paragraph at very end of document"""
    p=doc.add_paragraph()
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(24)
    p.paragraph_format.space_after=Pt(4)
    r=p.add_run(url)
    r.font.name=FN; r.font.size=Pt(9); r.font.color.rgb=GRAY; r.font.italic=True

def add_brand_body_start(doc, text):
    """Add brand text centered at top of body"""
    p=doc.add_paragraph()
    p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(4)
    p.paragraph_format.space_after=Pt(12)
    shd_para(p, 'F0F4FA')
    r=p.add_run(text)
    r.font.name=FN; r.font.size=Pt(10); r.font.color.rgb=NAVY; r.font.bold=True
    # Border bottom
    pPr=p._p.get_or_add_pPr(); pb=OxmlElement('w:pBdr')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single')
    b.set(qn('w:sz'),'4'); b.set(qn('w:space'),'1'); b.set(qn('w:color'),'244169')
    pb.append(b); pPr.append(pb)

# ── Load and patch ─────────────────────────────────────────────────────────────
doc = Document(DOCX_PATH)

# Remove existing section breaks (keep content, strip section headers/footers)
# Re-set header and footer (clears old ones)
set_header(doc, BRAND_TEXT)
set_footer(doc, BRAND_TEXT)

# Insert brand text right after the title (first real body paragraph)
# Find first non-empty paragraph after the title
paras = doc.paragraphs
title_para = paras[0]  # first para = title

# Insert new paragraph AFTER title
# Use the title para's index + 1
insert_idx = 0
for i, p in enumerate(paras):
    if p.text.strip() and i > 0:
        insert_idx = i
        break

# Insert brand body text at insert_idx
new_p = doc.paragraphs[insert_idx].insert_paragraph_before()
new_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
new_p.paragraph_format.space_before = Pt(4)
new_p.paragraph_format.space_after  = Pt(14)
r = new_p.add_run(BRAND_TEXT + "  |  " + BRAND_URL)
r.font.name = FN; r.font.size = Pt(10); r.font.color.rgb = NAVY; r.font.bold = False

# Add URL at very end
add_url_last_page(doc, BRAND_URL)

# Save
doc.save(DOCX_PATH)
sz = os.path.getsize(DOCX_PATH) // 1024
print(f"[OK] Patched: {DOCX_PATH}  ({sz} KB)")
print("Changes:")
print("  - Header: logo + brand text (centered, navy)")
print("  - Body start: brand text (centered, blue background)")
print("  - Footer: brand text + URL (centered)")
print("  - Last page: URL at bottom (centered, gray italic)")