"""Remove header/footer, put brand in body start + body end"""
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

LOGO_PATH = r"I:\Portraitpay ai\Logo 设计\PortraitpayAI.png"
BRAND_TEXT = "This template was generated by PortraitPay AI"
BRAND_URL  = "portraitpayai.com"
EN_DIR     = r"I:\Portraitpay ai\Doc\合同模板设计\EN"
DOCX_PATH  = os.path.join(EN_DIR, "01-Standard-License-Agreement.docx")

NAVY = RGBColor(0x24,0x41,0x69)
GRAY = RGBColor(0x60,0x60,0x60)
FN   = "Arial"

def clear_header_footer(doc):
    for sec in doc.sections:
        for p in sec.header.paragraphs: p.clear()
        for p in sec.footer.paragraphs: p.clear()

def add_brand_top(doc):
    """Insert logo + brand text before first paragraph"""
    first_p = doc.paragraphs[0]

    # Logo paragraph
    p1 = first_p.insert_paragraph_before()
    p1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p1.paragraph_format.space_before = Pt(4)
    p1.paragraph_format.space_after  = Pt(6)
    p1.add_run().add_picture(LOGO_PATH, width=Inches(0.75))

    # Brand text paragraph
    p2 = first_p.insert_paragraph_before()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p2.paragraph_format.space_before = Pt(4)
    p2.paragraph_format.space_after  = Pt(14)
    r = p2.add_run(BRAND_TEXT)
    r.font.name=FN; r.font.size=Pt(10); r.font.color.rgb=NAVY; r.font.bold=True

    # Separator line
    p3 = first_p.insert_paragraph_before()
    p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p3.paragraph_format.space_before = Pt(2)
    p3.paragraph_format.space_after  = Pt(0)
    pPr = p3._p.get_or_add_pPr()
    pb  = OxmlElement('w:pBdr')
    bot = OxmlElement('w:bottom')
    bot.set(qn('w:val'),'single'); bot.set(qn('w:sz'),'6')
    bot.set(qn('w:space'),'1'); bot.set(qn('w:color'),'244169')
    pb.append(bot); pPr.append(pb)

def add_url_bottom(doc):
    """Append URL as final paragraph"""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(20)
    p.paragraph_format.space_after  = Pt(6)
    # Top border
    pPr = p._p.get_or_add_pPr()
    pb  = OxmlElement('w:pBdr')
    top = OxmlElement('w:top')
    top.set(qn('w:val'),'single'); top.set(qn('w:sz'),'4')
    top.set(qn('w:space'),'1'); top.set(qn('w:color'),'CCCCCC')
    pb.append(top); pPr.append(pb)
    r = p.add_run(BRAND_URL)
    r.font.name=FN; r.font.size=Pt(9); r.font.color.rgb=GRAY; r.font.italic=True

doc = Document(DOCX_PATH)
clear_header_footer(doc)
add_brand_top(doc)
add_url_bottom(doc)
doc.save(DOCX_PATH)
sz = os.path.getsize(DOCX_PATH)//1024
print(f"[OK] Done ({sz} KB)")
print("  - Header/Footer: cleared")
print(f"  - Body top: logo + brand text")
print(f"  - Body bottom: {BRAND_URL}")