"use client";

/**
 * /report/[reportNumber] — Public Infringement Report View
 * No login required.
 */

import React, { useEffect, useState } from "react";
import Link from "next/link";
import ThemeToggle from "@/components/ThemeToggle";
import { useParams } from "next/navigation";

function typeLabel(v: string) {
  const map: Record<string, string> = {
    AI_FACE_CLONE: "AI Face Clone / Digital Human",
    VOICE_CLONE: "Voice Clone",
    AI_SHORT_DRAMA: "AI Short Drama Infringement",
    UNAUTHORIZED_USE: "Unauthorized Use",
    EXPIRED_LICENSE: "Expired License",
    SCOPE_VIOLATION: "Scope Violation",
    RESALE: "Resale/Illegal Transfer",
    DEEPFAKE: "Synthetic Media",
    OTHER: "Other",
  };
  return map[v] ?? v;
}

function platformLabel(v: string) {
  const map: Record<string, string> = {
    youtube: "YouTube", douyin: "Douyin", kuaishou: "Kuaishou",
    xiaohongshu: "Xiaohongshu", bilibili: "Bilibili", weibo: "Weibo",
    toutiao: "Toutiao", weixin: "WeChat Video", instagram: "Instagram",
    tiktok: "TikTok", other: "Other",
  };
  return map[v] ?? v;
}

interface ReportData {
  reportNumber: string;
  status: string;
  reportedName: string;
  reportedEmail: string;
  phone: string | null;
  infringementType: string;
  infringementTypeLabel: string;
  platformName: string | null;
  platformNameLabel: string | null;
  platformUrl: string | null;
  description: string | null;
  evidenceUrls: string[];
  generatedAt: string;
}

export default function ReportViewPage() {
  const { reportNumber } = useParams<{ reportNumber: string }>();
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!reportNumber) return;
    fetch(`/api/report/${reportNumber}`)
      .then((r) => r.json())
      .then((j) => {
        if (j.success) setReport(j.data);
        else setError(j.message || "Report not found");
      })
      .catch(() => setError("Failed to load report"))
      .finally(() => setLoading(false));
  }, [reportNumber]);

  function buildReportText() {
    if (!report) return "";
    const lines = [
      "INFRINGEMENT REPORT",
      "====================",
      "",
      `Report ID: ${report.reportNumber}`,
      `Generated: ${new Date(report.generatedAt).toLocaleString("en-US", { timeZone: "Asia/Shanghai" })}`,
      "",
      "--- REPORTER ---",
      `Name: ${report.reportedName}`,
      `Email: ${report.reportedEmail}`,
      report.phone ? `Phone: ${report.phone}` : null,
      "",
      "--- INFRINGER ---",
      `Name: ${report.reportedName}`,
      `Email: ${report.reportedEmail}`,
      "",
      "--- INFRINGEMENT ---",
      `Type: ${report.infringementTypeLabel}`,
      `Platform: ${report.platformNameLabel || "Not specified"}`,
      report.platformUrl ? `URL: ${report.platformUrl}` : null,
      "",
      "--- DESCRIPTION ---",
      report.description || "(No description provided)",
      "",
      "--- EVIDENCE LINKS ---",
      ...report.evidenceUrls.map((u, i) => `[${i + 1}] ${u}`),
      "",
      "This report is generated by PortraitPay AI for reference only.",
      "It does not constitute legal advice.",
      "For formal legal action, consult a licensed attorney.",
      "",
      "Issued by PortraitPay AI — www.portraitpayai.com",
    ];
    return lines.filter(Boolean).join("\n");
  }

  function handleCopy() {
    navigator.clipboard.writeText(buildReportText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-950 flex items-center justify-center">
        <div className="text-gray-500 dark:text-gray-400">Loading report...</div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-950 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Report Not Found</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-6">{error || "This report does not exist."}</p>
          <Link href="/" className="text-purple-600 hover:underline">Return Home</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <header className="sticky top-0 z-30 bg-white/80 dark:bg-gray-900/80 backdrop-blur border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-2xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="text-sm text-gray-500 hover:text-gray-900 dark:hover:text-white">← Back</Link>
          <ThemeToggle />
        </div>
      </header>
      <main className="max-w-2xl mx-auto px-6 py-12">
        <div className="text-center mb-6">
          <div className="w-16 h-16 rounded-full bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center mx-auto mb-4">
            <span className="text-3xl">📋</span>
          </div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">Infringement Report</h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            ID: <span className="font-mono font-semibold text-purple-600">{report.reportNumber}</span>
          </p>
        </div>

        <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-700 overflow-hidden mb-6">
          <div className="bg-purple-50 dark:bg-purple-900/20 px-6 py-4 border-b border-purple-100 dark:border-purple-800">
            <div className="flex items-center justify-between">
              <h2 className="font-semibold text-purple-700 dark:text-purple-300">Report Summary</h2>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white text-xs font-medium rounded-lg transition-colors"
              >
                {copied ? (
                  <><svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg> Copied!</>
                ) : (
                  <><svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg> Copy Report</>
                )}
              </button>
            </div>
          </div>
          <div className="p-6">
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-xs text-gray-400 mb-0.5">Reporter</p>
                <p className="font-medium text-gray-900 dark:text-white">{report.reportedName}</p>
                <p className="text-xs text-gray-500">{report.reportedEmail}</p>
              </div>
              <div>
                <p className="text-xs text-gray-400 mb-0.5">Type</p>
                <p className="font-medium text-gray-900 dark:text-white">{report.infringementTypeLabel}</p>
              </div>
              <div>
                <p className="text-xs text-gray-400 mb-0.5">Platform</p>
                <p className="font-medium text-gray-900 dark:text-white">{report.platformNameLabel || "—"}</p>
              </div>
              <div>
                <p className="text-xs text-gray-400 mb-0.5">Submitted</p>
                <p className="font-medium text-gray-900 dark:text-white text-xs">
                  {new Date(report.generatedAt).toLocaleDateString("en-US", { timeZone: "Asia/Shanghai" })}
                </p>
              </div>
            </div>
            {report.description && (
              <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700">
                <p className="text-xs text-gray-400 mb-1">Description</p>
                <p className="text-sm text-gray-700 dark:text-gray-300">{report.description}</p>
              </div>
            )}
            {report.evidenceUrls.length > 0 && (
              <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700">
                <p className="text-xs text-gray-400 mb-1">Evidence ({report.evidenceUrls.length})</p>
                {report.evidenceUrls.map((u, i) => (
                  <p key={i} className="text-xs font-mono text-purple-600 dark:text-purple-400 truncate">{u}</p>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-semibold text-gray-900 dark:text-white text-sm">Full Report Text — Copy & Paste Below</h2>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 text-xs font-medium rounded-lg transition-colors"
            >
              {copied ? "Copied!" : "Copy All"}
            </button>
          </div>
          <textarea
            readOnly
            value={buildReportText()}
            rows={20}
            className="w-full text-xs font-mono bg-gray-50 dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded-xl border border-gray-200 dark:border-gray-700 p-4 resize-none"
          />
        </div>

        <p className="text-xs text-center text-gray-400 mt-6">
          This report is for reference only and does not constitute legal advice.
          For formal legal action, consult a licensed attorney or file a police report.
        </p>
      </main>
    </div>
  );
}